### ISSUE TITLE
ch5 - pg 179 suggestion

### ISSUE THREAD

**Issue by nickvazz** [backstopmedia/tensorflowbook#7]
Hey, Really enjoying the book!

A few pages earlier you suggested adding a folder for the exporting of the dog data set. 
Right before you start the `def write_records_file(...)`, it seems it would be useful to mention adding the output/training-images and output/testing-images to your directories to avoid the error of running the ipynb for this section (CCN Implementation).

Thanks!

**Comment by samjabrahams** [comment]
@nickvazz thanks for the heads up! We'll try to add some clarity here to make sure people don't run into any problems. Once this is updated in the book's master files, we'll close this issue.

**Comment by samjabrahams** [comment]
Hi @nickvazz - sorry for the delay between responses. I believe that the book already informs users to download the dogs dataset and extract it to a directory called `imagenet-dogs` in the first paragraph under "Stanford Dogs Dataset". I'm going to close this for now, but please let me know if you have any additional feedback.
